### PR TITLE
Fixes to Familiar, Animal companion, and class abilties sheets. These fixes also make XLSM/ODS 'save as' work without error

### PR DESCRIPTION
**Pull request by timoc**
- Fixed broken defnition of Draconic Words in class abilities sheet - should be (Su) not some wierd unicode
- fixed dnn73 issue in wizard familiar sheet (should be DI74, DJ73 etc.)
- fixed dnn73 in animal companion sheet (should be DI74, DJ73 etc.)

Still has a 'random' external document link embedded in it, which causes errors when loaded.

Can now be used as an XLSM file.

Started using myself as an XLSM, some range definitions may be misdefined, but as far as i can tell that is in the original XLS version.

### CODE REVIEW

**Comment by Heliomance** [comment]
What did you do to make XLSM work properly?

**Comment by timoc** [comment]
What do you mean Properly? 
What were the problems you noticed?
The changes i made from the 'original' sheet were to remove the errors, and unsupported macros. 
the dmm changes were broken forumlas in the animal companion sheet
the other changes were macros attached to the buttons on the option pages.

**Comment by Heliomance** [comment]
Wait - the option page buttons don't work properly anymore? Damn, I shouldn't have merged that then. That's an issue.

**Comment by timoc** [comment]
No i'm sure i fixed the options macro too :)

**Comment by TwistedFaith84** [comment]
@timoc I think she meant in the version she released

**Comment by Heliomance** [comment]
No, I think I misread his comment - I read that he'd removed the macros on some of the buttons as they didn't work with XLSM.

**Comment by TwistedFaith84** [comment]
Ah ok sorry

**Pull request merged**
